config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create', as: 'create_session'
  get 'auth/failure', to: redirect('/admin')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'maintenance', to: 'sessions#maintenance_mode'
  get 'privacy', to: 'application#privacy'
  resources :songs, except: ["show"]
  resources :books, except: ["show"]
  get '/songs/:id', to: redirect('/%{id}')

  root to: 'songs#app'
  get '/books', to: 'songs#app'
  get '/:book/:s', to: 'songs#app', constraints: { s: /[i0-9]+/ }
  get  '/books/admin', to: 'books#admin', as: :admin_books
  get  '/books/admin/new', to: 'books#new',  as: :new_admin_book
  post '/books/admin/create',to: 'books#create', as: :create_admin_book
  get  '/books/admin/:book_slug', to: 'books#list', as: :admin_book
  get  '/books/admin/:book_slug/edit', to: 'books#edit', as: :edit_admin_book
  patch '/books/admin/:book_slug', to: 'books#update', as: :update_admin_book
  delete '/books/admin/:book_slug', to: 'books#destroy', as: :delete_admin_book

  get 'edit', to: 'songs#edit' # shortcut when wanting to edit a song from main app
  get '/:s/e', to: 'songs#edit'
  get '/:s', to: 'songs#app', s: /[0-9]+/
  get 'admin', to: 'songs#admin'
  get 'admin/example', to: 'songs#admin_example'
  get 'admin/example_with_tunes', to: 'songs#admin_example_with_tunes'
  get 'taketime', to: 'take_time#take_time'
  get '/:s/print', to: 'songs#print', s: /[0-9]+/
  get '/:s/p', to: 'songs#print', s: /[0-9]+/

  namespace :api do
    namespace :v1 do
      get 'app_data', to: 'songs#app_data'
      get 'languages', to: 'songs#languages'
      get 'admin_songs', to: 'songs#admin_songs'
    end
  end

  namespace :api do
    namespace :v2 do
      get 'app_data', to: 'songs#app_data'
      get 'languages', to: 'songs#languages'
      get 'admin_songs', to: 'songs#admin_songs'
      get 'custom_book_search', to: 'songs#custom_book_search'
    end
  end
end

app/controllers/api/v1/songs_controller.rb
# DEPRECATED
# This version is no longer supported

class Api::V1::SongsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def app_data
    songs_to_sync = Song.where('updated_at > ?', client_updated_at).for_language(params[:language])
    books_to_sync = Book.where('updated_at > ?', client_updated_at).for_language(params[:language])
    render json: {
      deprecation_warning: 'WARNING: This api version is deprecated. Please use v2 instead, as v1 is no longer supported. Song data will still come through, but book data has been removed.',
      songs: songs_to_sync.app_data,
      books: [],
      references: [],
      destroyed: { songs: [],
                   references: [],
                   books: [] },
      songCount: Song.for_language(params[:language]).count,
      },
      status: 200
  end

  def languages
    render json: {
      deprecation_warning: 'WARNING: This api version is deprecated. Please use v2 instead, as v1 is no longer supported. Song data will still come through, but book data has been removed.',
      languages: Song.distinct.pluck(:lang).without('english').prepend('english')
    }
  end

  private

  def client_updated_at
    return @client_updated_at if @client_updated_at.present?

    updated_at = params[:updated_at].presence&.to_i || 0
    seconds = updated_at / 1000
    milliseconds = updated_at % 1000
    @client_updated_at = Time.at(seconds, milliseconds, :millisecond).utc
  end
end

app/controllers/api/v2/songs_controller.rb
class Api::V2::SongsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def app_data
    songs_to_sync = Song.where('updated_at >= ?', client_updated_at).for_language(params[:language])
    books_to_sync = Book.where('updated_at >= ?', client_updated_at).for_language(params[:language])

    render json: {
      songs: songs_to_sync.app_data,
      books: books_to_sync.app_data,
      destroyed: { songs: Song.deleted_after(client_updated_at).pluck(:id),
                   books: Book.deleted_after(client_updated_at).pluck(:id) },
      songCount: Song.for_language(params[:language]).count,
      data_updated_between: [client_updated_at, Time.now.utc]
    },
      status: 200
  end

  def languages
    render json: { languages: Song.languages }
  end

  def admin_songs
    render json: {songs: {duplicates: duplicate_songs,
                          changed: recently_changed_songs - duplicate_songs,
                          unchanged: songs_for_admin - recently_changed_songs - duplicate_songs}}, status: 200
  end

  def custom_book_search
    render json: {songs: songs_for_admin}, status: 200
  end

  private

  def duplicate_songs
    # Only super admin can see duplicates, because it crashes performance
    return [] unless (super_admin && !params[:search].present?)

    recently_changed_ids = Song.recently_changed.pluck(:id) # only query recent songs to speed things up
    @duplicate_songs ||= sort_songs(Song.where(id: recently_changed_ids)
                                        .duplicate_titles
                                        .limit(10)
                                        .map(&:admin_entry))
  end

  def recently_changed_songs
    return [] if params[:search].present?

    @recently_changed_songs ||= sort_songs(Song.search(params[:search])
                                               .recently_changed
                                               .limit(50)
                                               .map(&:admin_entry))
  end

  def songs_for_admin
    sort_songs(Song.search(params[:search])
                   .limit(100)
                   .map(&:admin_entry))
  end

  def client_updated_at
    return @client_updated_at if @client_updated_at.present?

    updated_at = params[:updated_at].presence&.to_i || 0
    seconds = updated_at / 1000
    milliseconds = updated_at % 1000
    @client_updated_at = Time.at(seconds, milliseconds, :millisecond).utc
  end

  def sort_songs(songs)
    return songs unless songs.present?

    search = clean_for_sorting(params[:search].to_s)
    songs.sort_by do |s|
      title = clean_for_sorting(s[:title])

      case
      when title.match?(/^#{search}/) # If search is the start of the title, top priority
        "0#{title}"
      when title.match?(search) # If title contains search, next priority
        "1#{title}"
      else
        "2#{title}" # Else just sort by title
      end
    end
  end

  def clean_for_sorting(str)
    return '' unless str.present?

    str.gsub(/[[:punct]]/, "").downcase
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:new, :edit, :create, :update, :destroy]
  before_action :check_maintenance
  before_action :adjust_lang_params, only: [:create, :update]

  # Preloaded data is to send the data directly with the html
  # Usually the client gets the data from our api
  # But by sending the data of the url the user is loading,
  # we can deliver the data instantly while the rest is
  # still loading via api.
  def app
    @book_slug = params[:book]
    @book_from_url = Book.find_by(slug: @book_slug) if @book_slug.present?
    if(params[:s].present? && params[:s] != 'i')

      # If a book's slug is in the url, then the id param will be the book's
      # index, so we need to convert it to the song's id:
      if @book_slug.present?
        @song_id = @book_from_url&.song_id_from_index(params[:s])
      end

      song = Song.find(@song_id || params[:s])
      if song.present?
        @title = song.title # sets page title in application.html.erb
        @song_id = params[:s]
        @preloaded_song = song.app_entry
        @preloaded_book_refs = Book.with_song(song).book_refs_for(song)
      end
    end
    render layout: "robot_visible"
  end

  def admin
  end

  def admin_example
    @song = Song.new(lyrics: example_lyrics)
  end

  def admin_example_with_tunes
    @song = Song.new(lyrics: example_lyrics_with_tunes)
    render :admin_example
  end

  def show
  end

  def print
    @song = Song.find(params[:s])
  end

  def new
    @song = Song.new
  end

  def edit
  end

  def create
    @song = Song.new(song_params)

    if @song.duplicate?
      redirect_to admin_path, notice: "Song was successfully created. #{song_flash_link(@song.duplicate)} to view in app."
    elsif @song.save
      email_diff_to_overseers(@song)
      Audit.create(user: current_user, song: @song, time: Time.zone.now)
      redirect_to admin_path, notice: "Song was successfully created. #{song_flash_link(@song)} to view in app."
    else
      render :new
    end
  end

  def update
    @song = Song.find(params[:id])

    if @song.update(song_params)
      email_diff_to_overseers(@song)
      Audit.create(user: current_user, song: @song, time: Time.zone.now)
      redirect_to admin_path, notice: "Song was successfully updated. #{song_flash_link(@song)} to view in app."
    else
      render :edit
    end
  end

  def destroy
    if @song.destroy_with_audit(current_user)
      redirect_to admin_path, notice: 'Song was successfully destroyed.'
    else
      render :back
    end
  end

  private

  def email_diff_to_overseers(song)
    changes = song.previous_changes.except(:updated_at, :created_at, :id)
    SongMailer.song_changed(song, changes).deliver_later unless changes.empty?
  end

  def song_flash_link(song)
    view_context.link_to 'Click here', song_path(song), class: 'flash_link'
  end

  def adjust_lang_params
    if params[:song][:lang] == "new_lang"
      params[:song][:lang] = params[:song][:new_lang]
    end
  end

  def set_song
    @song = Song.find(params[:id] || params[:s])
  end


  def song_params
    result = params.require(:song).permit(:lyrics, :title, :lang, language_links: [])
    result[:language_links] = result[:language_links].first.split(',') if result[:language_links].present?
    result
  end

  def example_lyrics
"
# This is a comment.

# If there is a comment for the recommended capo like the one below, users can tap it to transpose the chords.

# Capo 2

You can enter [C]chords in [Am]the ex[F]act place you want them [G]with squ[E7]are b[C]rackets like this.

  Chorus lines are
  made with
  2 spaces
  before each line

1
Stanza numbers go above the
First line of the stanza

2
For languages like spanish,
Where you want to merge the start and end
of a word, you can use_underscores to link words
like_this.

This example opened in a new tab. The song you were working on is still there in the previous tab.

Advanced:
- You can type '\\' (easy for physical keyboards) or '$' (easy for phone keyboards) to insert square brackets for adding chords quickly.
- You can type lowercase chords inside square brackets and they will be automatically capitalized."
  end

  def example_lyrics_with_tunes
"### Original tune
# You can see the example here for adding multiple tunes to the same song. This is a nice way to declutter songs with many tunes, and especially tunes where the wording changes (e.g. one tune with a chorus, one without)

# If you are adding a new tune, please also name the original tune, with the triple # format.

# Capo 1

1
Be [G]Thou su[D]preme, O [G]Jesus [C]Christ,
Nor [Am]creed, nor [D]form, nor [G]word,
Nor [D]holy [G]Church, nor [B7]human [Em]love,
Com[G]pare with [Am]Thee, [D]my [G]Lord!

2
Be Thou supreme, O Jesus Christ,
Thy love has conquered me;
Beneath Thy Cross I die to self,
And live alone to Thee.

3
Be Thou supreme, O Jesus Christ,
My inmost being fill;
So shall I think as Thou dost think,
And will as Thou dost will.

4
Be Thou supreme, O Jesus Christ,
Thy life transfigure mine;
And through this veil of mortal flesh,
Lord, let Thy splendor shine.

5
Be Thou supreme, O Jesus Christ,
My soul exults in Thee;
To be Thy slave, to do Thy will,
Is my felicity.

### New tune (with chorus)

1
[C]Be Thou su[G]preme, O [Am]Jesus Christ,
[F]Thy love has conquered [G]me;
[C]Beneath Thy [G]Cross I [Am]die to self,
[F]And live a[G]lone to [C]Thee.

  Be Thou su[F]prem[G]e, O Jesus [C]Christ,
  Nor creed, nor [F]for[G]m, nor [C]word,
  Nor holy [F]Church, [G]nor [Am]human love,
  [F]Compare with [G]Thee, my [C]Lord!

2
Be Thou supreme, O Jesus Christ,
My inmost being fill;
So shall I think as Thou dost think,
And will as Thou dost will.

3
Be Thou supreme, O Jesus Christ,
Thy life transfigure mine;
And through this veil of mortal flesh,
Lord, let Thy splendor shine.

4
Be Thou supreme, O Jesus Christ,
My soul exults in Thee;
To be Thy slave, to do Thy will,
Is my felicity.


# Verse 1 of the original hymn has
# become the chorus for this tune"
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= link_to 'How do I format this?', admin_example_path, target: :_blank, class: 'btn-help' %>
<%= link_to 'How do I add multiple tunes?', admin_example_with_tunes_path, target: :_blank, class: 'btn-help' %>
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= react_component(
    'SongForm',
    song: song,
    languages: Song.languages,
    bookRefs: Book.with_song(song).book_refs_for(song)) %>
  <div class="actions text-center">
    <%= f.submit class: "btn btn-update" %>
<% end %>
    <%= button_to 'Remove', song_path(song), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-delete" if song.persisted? && (super_admin || song.created_at > 7.days.ago) %>
  </div>

app/views/songs/admin.html.erb
<%= render 'nav' %>
<%= render 'flash' %>

<h1>Songbase Admin</h1>

<div class="new-song-btn">
  <%= link_to 'New Song', new_song_path, class: "new_song_link" %>

  <%= link_to 'Books Admin', '/books/admin', class: "new_song_link" %>
</div>

<%= react_component(
  'AdminSongList',
  { songs: @songs.map(&:admin_entry) },
  superAdmin: super_admin,
  settings: {
    languages: Song.languages
  })
%>

app/views/songs/admin_example.html.erb
<h1 class="admin-root-title">
  <%= link_to "Example Song", '_self', onclick: 'window.close();' %>
</h1>

<%= react_component(
    'SongForm',
    song: @song,
    languages: Song.languages,
    exampleForm: true) %>

app/views/songs/app.html.erb
<%=
  react_component(
    'SongApp',
    song_id: @song_id,
    preloaded_song: @preloaded_song,
    preloaded_current_book: @book_from_url,
    preloaded_book_refs: @preloaded_book_refs
  )
%>

<!-- Start of StatCounter Code for Default Guide -->
<script type="text/javascript">
var sc_project=11546513;
var sc_invisible=1;
var sc_security="f7a2e87a";
var sc_script = document.createElement('script');
sc_script.type = 'text/javascript'; sc_script.async = true;
sc_script.src = ('https:' == document.location.protocol ? 'https://secure.' : 'http://www.') + 'statcounter.com/counter/counter.js';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(sc_script, s);
</script>
<!-- End of StatCounter Code for Default Guide -->

app/views/songs/edit.html.erb
<h1 class="admin-root-title"><%= link_to "Edit Song", admin_path %></h1>
<hr>
<div class="admin-comment">
Dear saints, when editing songs:
  <ul>
    <li>Please respect the original writings. Adding chords and fixing typos are very helpful. However, (especially with the LSM hymnal) please do not change the lyrics or offer alternate lines/stanzas.</li>
    <li>Please choose the simpler version of chords, whenever there is a choice. Many musicians in the church are learners and beginners, and they need simple music to follow.</li>
  </ul>
</div>
<hr>
<%= render 'form', song: @song %>

app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song[:title] %></td>
        <td><%= link_to 'Show', song[:model] %></td>
        <td><%= link_to 'Edit', edit_song_path(song[:model]) %></td>
        <td><%= link_to 'Destroy', song[:model], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1 class="admin-root-title"><%= link_to "New Song", admin_path %></h1>

<%= render 'form', song: @song %>

app/views/songs/print.html.erb
<div class="note">
  <p>Welcome to the print page! All lines start with a tab (but verse numbers are on the left side of the tab).</p>
  <p>To format this nicely, copy to your favorite text editor (google docs is a great choice), and set the left tab stops in your document. Choruses have two tabs, so set a second left tab stop for them.</p>
  <p>Depending on your editor, you may need to paste with <b>ctrl + shift + v</b>, to get the formatting to adjust the text properly.</p>
  <p>Look out for comments in the lyrics (lines that start with #). It is good to format them differently to the song (e.g. italics, grey color, etc).</p>
  <p>Ctrl + A is a quick way to select all text. This grey text will not be selected.</p>
</div>
<div class="song-print"><%= @song.print_format %>

app/views/songs/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>
<div class="centered">
  <h4 class="song-title"><%= @song.title %></h4>
  <br />
  <%= react_component('SongDisplay', lyrics: @song.lyrics) %>
  <br />
  <div class="bottom-nav-buttons">
    <%= link_to 'Edit', edit_song_path(@song) %> |
    <%= link_to 'Back', admin_path %>
  </div>
</div>