config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create', as: 'create_session'
  get 'auth/failure', to: redirect('/admin')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'maintenance', to: 'sessions#maintenance_mode'
  get 'privacy', to: 'application#privacy'
  resources :songs, except: ["show"]
  resources :books, except: ["show"]
  get '/songs/:id', to: redirect('/%{id}')

  root to: 'songs#app'
  get '/books', to: 'songs#app'
  get '/:book/:s', to: 'songs#app', constraints: { s: /[i0-9]+/ }
  get  '/books/admin', to: 'books#admin', as: :admin_books
  get  '/books/admin/new', to: 'books#new',  as: :new_admin_book
  post '/books/admin/create',to: 'books#create', as: :create_admin_book
  get  '/books/admin/:book_slug', to: 'books#list', as: :admin_book
  get  '/books/admin/:book_slug/edit', to: 'books#edit', as: :edit_admin_book
  patch '/books/admin/:book_slug', to: 'books#update', as: :update_admin_book
  delete '/books/admin/:book_slug', to: 'books#destroy', as: :delete_admin_book

  get 'edit', to: 'songs#edit' # shortcut when wanting to edit a song from main app
  get '/:s/e', to: 'songs#edit'
  get '/:s', to: 'songs#app', s: /[0-9]+/
  get 'admin', to: 'songs#admin'
  get 'admin/example', to: 'songs#admin_example'
  get 'admin/example_with_tunes', to: 'songs#admin_example_with_tunes'
  get 'taketime', to: 'take_time#take_time'
  get '/:s/print', to: 'songs#print', s: /[0-9]+/
  get '/:s/p', to: 'songs#print', s: /[0-9]+/

  namespace :api do
    namespace :v1 do
      get 'app_data', to: 'songs#app_data'
      get 'languages', to: 'songs#languages'
      get 'admin_songs', to: 'songs#admin_songs'
    end
  end

  namespace :api do
    namespace :v2 do
      get 'app_data', to: 'songs#app_data'
      get 'languages', to: 'songs#languages'
      get 'admin_songs', to: 'songs#admin_songs'
      get 'custom_book_search', to: 'songs#custom_book_search'
    end
  end
end

app/models/book.rb
# For optimal client-side data structure, and also to compact books down to a
# single row in the db per book, there are some unusual db fields in this
# model.
# - Languages are stored as an array field, as one book could contain songs
#   of more than one language.
# - Songs are stored as a jsonb field. The format for
#   this is {song_id => index_in_book, other_song_id => other_index_in_book}.
#   Adding a song:  my_book.songs[song.id] = 1; my_book.save

class Book < ApplicationRecord
  before_validation :assign_default_owner,  on: [:create, :update]
  before_validation :generate_slug, on: [:create, :update]
  default_scope -> { where(deleted_at: nil) }

  # The weird syntax is for postgres Array types
  scope :for_language, ->(language) { language.present? ? where("? = ANY (languages)", language) : all }

  # Keeping this commented code as a reference for querying "does this
  # top-level key exist in this jsonb field", very useful:
  #
  scope :with_song, ->(song) { Book.where("songs ? ':id'", id: song.id) }


  # For now (17 Aug 2023) we will not delete books from db. If it's a problem
  # ~12 months from now we can try a "delete everything that hasn't been
  # updated for 6 months except the important books" kinda thing
  scope :deleted_after, ->(last_updated_at) { unscoped.where('deleted_at >= ?', last_updated_at).where('created_at < ?', last_updated_at) }

  def self.hymnals
    where(slug: ["spanish_hymnal", "english_hymnal", "german_hymnal", "french_hymnal", "hinos"])
  end

  def self.english_hymnal; find_by(slug: "english_hymnal"); end
  def self.spanish_hymnal; find_by(slug: "spanish_hymnal"); end
  def self.german_hymnal; find_by(slug: "german_hymnal"); end
  def self.french_hymnal; find_by(slug: "french_hymnal"); end
  def self.portuguese_hymnal; find_by(slug: "hinos"); end
  def self.dutch_hymnal; find_by(slug: "liedboek"); end
  def self.chinese_hymnal; find_by(slug: "chinese_hymnal"); end
  def self.korean_hymnal; find_by(slug: "korean_hymnal"); end

  def self.book_refs_for(song)
    all.map { |book| [book.slug, book.name, book.songs[song.id.to_s]] }
  end

  def self.find(param)
    if param =~ /[^0-9]/
      self.find_by(slug: param)
    else
      super
    end
  end

  def self.app_data
    self.all.map(&:app_entry)
  end

  def song_id_from_index(index)
    songs.key(index.to_s)
  end

  def song_at(index)
    id = song_id_from_index(index)
    Song.find(id) if id
  end

  def song_records
    Song.where(id: songs.keys)
  end

  def app_entry
    {
      id: id,
      name: name,
      slug: slug,
      songs: songs,
      languages: languages,
      owners: owners
    }
  end

  private 

  def assign_default_owner
      if owners.blank?
        self.owners = [{ name: User.system_user.name, email: User.system_user.email }]
      end
  end

  def generate_slug
    return if name.blank?

    if name_changed? || slug.blank?
      base_slug = name.parameterize(separator: '_')

      candidate = base_slug
      counter = 2
      while Book.exists?(slug: candidate) && (self.slug != candidate)
        candidate = "#{base_slug}_#{counter}"
        counter += 1
      end

      self.slug = candidate
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :list]
  before_action :load_songs, only: [:new, :edit, :create, :update, :list]

  def list
    @book = Book.find(params[:book_slug])
    song_ids = @book.songs.keys.map(&:to_i)
    @songs = Song.where(id: song_ids).to_a
  end

  def admin
    @books = Book.all
  end

  def new
    @book = Book.new
    @songs = Song.all
    render :new
  end

  def edit
    @book = Book.find_by!(slug: params[:book_slug])
    @songs = Song.all
    render :edit
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to admin_book_path(@book.slug), notice: "Book was successfully created"
    else
      render :new
    end
  end

  def update
    @book = Book.find(params[:book_slug])
    if @book.update(book_params)
      redirect_to admin_books_path, notice: "Book was successfully updated"
    else
      render :edit
    end
  end

  private

  def set_book
    @book = Book.find(params[:book_slug])
  end

  def load_songs
    @songs = Song.all
  end

  def book_params
    permitted = params.require(:book).permit(:name, :songs, :languages)

    permitted[:songs] = JSON.parse(permitted[:songs]) rescue {} if permitted[:songs].is_a?(String)
    permitted[:languages] = JSON.parse(permitted[:languages]) rescue [] if permitted[:languages].is_a?(String)

    permitted
  end
end

app/views/books/_flash.html.erb
<% if notice %>
  <p id="notice"><%= notice.html_safe %></p>
<% end %>
<% if alert %>
  <p id="alert"><%= alert %></p>
<% end %>

app/views/books/_form.html.erb
<%= form_for book, url: book.persisted? ? update_admin_book_path(book.slug) : create_admin_book_path, method: book.persisted? ? :patch : :post do |f| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= react_component("AdminBookForm", {
    songs: @songs,
    book: book,
  }) %>

  <div class="actions text-center">
    <%= f.submit "Save Book", class: "btn btn-update" %>
  </div>
<% end %>

<% can_delete = super_admin || (book.owners.any? { |owner| owner.email == current_user.email }) %>
<% if book.persisted? && can_delete %>
  <%= button_to "Delete Book", delete_admin_book_path(book.slug), method: :delete,
                data: { confirm: "Are you sure you want to delete this book?" },
                class: "btn btn-delete" %>
<% end %>

app/views/books/_nav.html.erb
<div class="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= google_sign_in_button image_tag('btn_google_signin_dark_normal_web@2x.png', alt: 'Google'), proceed_to: create_session_url(:google), class: 'sign_in_google' %>
  <% end %>
</div>

app/views/books/admin.html.erb
<%= render 'nav' %>
<%= render 'flash' %>

<h1>Songbase Admin</h1>

<div class="new-book-btn">
    <%= link_to 'New Book', '/books/admin/new', class: "new_book_link" %>
</div>

<%=
  react_component(
    'AdminBookList',
    { books: @books.map(&:app_entry) }
  )
%>

app/views/books/edit.html.erb
<h1 class="admin-root-title"><%= link_to "Edit Book", admin_books_path %></h1>
<hr>
<div class="admin-comment">
  Dear saints, when editing books:
  <ul>
    <li>You may update the book title, change the order of songs, and manage ownership (add or remove owners).</li>
    <li>Please avoid reordering songs unless necessary, as the current sequence may have been prayerfully considered for use in meetings or conferences.</li>
    <li>Deleting a book will permanently remove it for all users. Please ensure this is intentional before proceeding.</li>
    <li>Edit access to this book is limited to the listed owners below. Please consider carefully who should have ownership.</li>
  </ul>
</div>
<hr>
<%= render 'form', songs: @songs, book: @book %>

app/views/books/list.html.erb
<%= render 'nav' %>
<%= render 'flash' %>

<h1>
  <%= link_to @book.name, admin_books_path, class: "book-title-link" %>
</h1>

<%= react_component(
  'AdminBookDisplay',
  { songs: @songs, book: @book, superAdmin: super_admin }
) %>

app/views/books/new.html.erb
<h1 class="admin-root-title"><%= link_to "New book",  admin_books_path %></h1>

<%= render 'form', songs: @songs, book: @book %>